# Names and values match TelloPy
uint8 flip_forward=0
uint8 flip_left=1
uint8 flip_back=2
uint8 flip_right=3
uint8 flip_forwardleft=4
uint8 flip_backleft=5
uint8 flip_backright=6
uint8 flip_forwardright=7
#
# overload this message for diagnostics
uint8 move_forward=8
uint8 move_left=9
uint8 move_back=10
uint8 move_right=11
uint8 move_up=12
uint8 move_yawleft=13
uint8 move_down=14
uint8 move_yawright=15
uint8 move_fb_none=16
uint8 move_lr_none=17
uint8 move_ud_none=18
uint8 move_yaw_none=19


uint8 flip_command
